import airlinesData from '#lib/data/airlines.json';
import type { Airline } from '#lib/types.js';

// Generated by scripts/build-airlines.mjs. Server-only, like the airports.
const airlines = airlinesData as Airline[];
const byIata = new Map(airlines.map((a) => [a.iata, a]));
const byIcao = new Map(airlines.filter((a) => a.icao).map((a) => [a.icao!, a]));

const IATA_CODE = /^(?=.*[A-Z])[A-Z0-9]{2}$/;

export function airlineByIata(iata: string): Airline | undefined {
  return byIata.get(iata.trim().toUpperCase());
}

/**
 * Exact code match (IATA or ICAO) first, then names starting with the query,
 * then names containing it, each best-known first. A well-formed IATA code missing from the table
 * still comes back, so newer airlines can be picked by code.
 */
export function searchAirlines(query: string, limit = 8): Airline[] {
  const q = query.trim().toUpperCase();
  if (q.length < 2) return [];
  const exact = byIata.get(q) ?? byIcao.get(q);
  if (exact) return [exact];
  const prefix = airlines.filter((a) => a.name.toUpperCase().startsWith(q));
  const contains = airlines.filter((a) => !a.name.toUpperCase().startsWith(q) && a.name.toUpperCase().includes(q));
  const results = [...prefix, ...contains].slice(0, limit);
  if (results.length === 0 && IATA_CODE.test(q)) return [{ iata: q, name: `Airline ${q}` }];
  return results;
}
